# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_device_database'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device_database',
            name='device_ip',
        ),
        migrations.AddField(
            model_name='device_database',
            name='ip_address',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='device_database',
            name='os_version',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='community_string',
            name='community_string',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='device_database',
            name='device_name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
